//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4WebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagories
    {
        public Catagories()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public int RootLevel { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
