//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4WebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public Nullable<System.DateTime> RegistererDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
