//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Bills")]
    public partial class Bills: Entity
    {
        public Nullable<bool> IsCompany { get; set; }
        public string TaxNumber { get; set; }
        public string TaxOffice { get; set; }
        public string IdentityNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public int CityId { get; set; }
        public int TownId { get; set; }
        public int SubDistrictId { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string GsmNumber { get; set; }
        public string FaxNumber { get; set; }
        public string OrderNote { get; set; }
        public Nullable<decimal> Campaign { get; set; }
        public long OrderId { get; set; }
    }
}
