//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ChatLogs")]
    public partial class ChatLogs: Entity
    {
        public int SenderUserId { get; set; }
        public int ReceiverUserId { get; set; }
        public string Message { get; set; }
        public string Guid { get; set; }
        public string Ip { get; set; }
        public System.DateTime Date { get; set; }
    }
}
