//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Design;

    [Table("Credits")]
    public partial class Credits: Entity
    {
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CreditcardNumber { get; set; }
        public string CreditcardOwner { get; set; }
        public string SecureCode { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Installments { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Ip { get; set; }
    }
}
