//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Districts")]
    public partial class Districts: Entity
    {
        public int City_Id { get; set; }
        public int Town_Id { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
    }
}
