//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Orders")]
    public partial class Orders: Entity
    {
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> TransportTypeId { get; set; }
        public Nullable<int> RequesterUserId { get; set; }
        public Nullable<int> RequesterAddressId { get; set; }
        public Nullable<int> ResponderUserId { get; set; }
        public Nullable<int> ResponderAddressId { get; set; }
        public Nullable<int> ResponderFirmTypeId { get; set; }
        public Nullable<int> ResponderFirmId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBilling { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<bool> IsTransportFree { get; set; }
    }
}
