//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Products")]
    public partial class Products: Entity
    {
        public Nullable<long> EqualId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DenominationId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Barcode { get; set; }
        public string Explanation { get; set; }
        public string ImagePath0 { get; set; }
        public string ImagePath1 { get; set; }
        public string ImagePath2 { get; set; }
        public string ImagePath3 { get; set; }
        public string ImagePath4 { get; set; }
        public string ImagePath5 { get; set; }
        public string ImagePath6 { get; set; }
        public string ImagePath7 { get; set; }
        public string ImagePath8 { get; set; }
        public string ImagePath9 { get; set; }
        public string ImagePath10 { get; set; }
        public string VideoPath { get; set; }
        public Nullable<decimal> OfferedPrice { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<int> PriceCurrencyId { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public Nullable<int> RegistererId { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<int> FeedCount { get; set; }
        public string SpecialCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> ProductGroup_Id { get; set; }
        public Nullable<int> ProductPlace_Id { get; set; }
        public Nullable<int> ProductState_Id { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string Km { get; set; }
        public bool IsExchangable { get; set; }
        public bool AAS { get; set; }
        public bool ASR { get; set; }
        public bool HavaYastigiPerdeler { get; set; }
        public bool Immobilizer { get; set; }
        public bool ParkMesafeKontrol { get; set; }
        public bool EDB { get; set; }
        public bool HavaYastigiSurucu { get; set; }
        public bool ABS { get; set; }
        public bool Isofix { get; set; }
        public bool Alarm { get; set; }
        public bool EDL { get; set; }
        public bool HavaYastigiYan { get; set; }
        public bool LastikArizaGostergesi { get; set; }
        public bool ArkaGorusKamerasi { get; set; }
        public bool ESP { get; set; }
        public bool HavaYastigiYolcu { get; set; }
        public bool MerkeziKilit { get; set; }
        public bool SeritTakipSistemi { get; set; }
        public bool GeceGorus { get; set; }
        public bool UzaktanKumanda { get; set; }
        public bool Airmatic { get; set; }
        public bool TCS { get; set; }
        public bool YorgunlukTespitSistemi { get; set; }
        public bool Bas { get; set; }
        public bool AhsapDireksiyon { get; set; }
        public bool DeriDireksiyon { get; set; }
        public bool HafizaliKoltuklar { get; set; }
        public bool Koltukisitma { get; set; }
        public bool Sunroof { get; set; }
        public bool AnahtarsizCalistirabilme { get; set; }
        public bool DeriKoltuk { get; set; }
        public bool HizSabitleyici { get; set; }
        public bool Klima { get; set; }
        public bool BlueTooth { get; set; }
        public bool Telefon { get; set; }
        public bool AyarlanabilirDireksiyon { get; set; }
        public bool HidrolikDireksiyon { get; set; }
        public bool YolBilgisayari { get; set; }
        public bool ElektirikliIsitmaliCamlar { get; set; }
        public bool IsitmaliDireksiyon { get; set; }
        public bool SogutmaliTorpido { get; set; }
        public bool HeadUpDisplay { get; set; }
        public bool IleriGorusKamerasi { get; set; }
        public bool GeriGorusKamerasi { get; set; }
        public bool KolDayama { get; set; }
        public bool IleriIleriVitesler { get; set; }
        public bool AlasimJantlar { get; set; }
        public bool FarYikama { get; set; }
        public bool YagmurSensoru { get; set; }
        public bool CamTavan { get; set; }
        public bool Modifiyeli { get; set; }
        public bool SisFari { get; set; }
        public bool ElektirikliYanAynalar { get; set; }
        public bool FarSensoru { get; set; }
        public bool XenonFarlar { get; set; }
        public bool ParkSensoru { get; set; }
        public bool KatlanirAynalar { get; set; }
        public bool GeceSensoru { get; set; }
        public bool ArkaCamBuzCozucu { get; set; }
        public bool PanoramikOnCam { get; set; }
        public bool PanaromikCamTavan { get; set; }
        public bool HardTop { get; set; }
        public bool RadyoType { get; set; }
        public bool RadyoCD { get; set; }
        public bool Mp3Calabilme { get; set; }
        public bool NavigasyonTV { get; set; }
        public bool USBAUX { get; set; }
        public bool AUX { get; set; }
        public bool IPod { get; set; }
        public bool Hoparlor6 { get; set; }
        public bool CDDVDDegistirici { get; set; }
        public bool NotSmoked { get; set; }
        public bool FromForeigner { get; set; }
        public bool UrgentSale { get; set; }
        public bool Maturity { get; set; }
        public Nullable<int> ProductSeller { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public Nullable<int> DamageState { get; set; }
        public Nullable<int> GuarantySituation { get; set; }
        public Nullable<int> PublishDuration { get; set; }
        public Nullable<int> FuelType { get; set; }
        public Nullable<int> GearType { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> CaseType { get; set; }
        public Nullable<int> EngineCapacity { get; set; }
        public Nullable<int> EnginePower { get; set; }
        public Nullable<int> Traction { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<int> PlateNationality { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> District { get; set; }
        public string ServiceName { get; set; }
        public string ServiceAddress { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTelephone { get; set; }
        public string ServiceAuthor { get; set; }
        public string ServiceProperties { get; set; }
        public Nullable<int> ServicePoint { get; set; }
    }
}
