//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProductPlaces")]
    public partial class ProductPlaces: Entity
    {
        public string Name { get; set; }
        public Nullable<int> AutoServiceId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> AutoService_Id { get; set; }
        public Nullable<int> AutoService_Id1 { get; set; }
    
        public virtual AutoServices AutoServices { get; set; }
    }
}
