//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Tokens")]
    public partial class Tokens: Entity
    {
        public Nullable<int> UserId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
