//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("UserFriends")]
    public partial class UserFriends: Entity
    {
        public int UserId { get; set; }
        public int FriendUserId { get; set; }
        public Nullable<int> AutherTypeId { get; set; }
        public string OtherSettings { get; set; }
    }
}
