//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("UserProfile")]
    public partial class UserProfile: Entity2
    {
        public string UserName { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string eMail { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string HomePhone { get; set; }
        public string GSM { get; set; }
        public string WorkPhone { get; set; }
        public string Fax { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> EducationLevel { get; set; }
        public Nullable<int> Job { get; set; }
        public string ProfilePhoto { get; set; }
        public string TCid { get; set; }
        public string Password { get; set; }
    }
}
