//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("UserMessages")]
    public partial class UserMessages: Entity
    {
        public int SenderUserId { get; set; }
        public int ReceiverUserId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime SendingDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string AttachedFilePath { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
