//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using Dal.Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("UserFeedbacks")]
    public partial class UserFeedbacks: Entity
    {
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AutoServiceId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public Nullable<int> PleasedCount { get; set; }
        public Nullable<int> UnpleasedCount { get; set; }
    }
}
